### ISSUE TITLE
Handle empty list in select_multiple when esc is pressed

### ISSUE THREAD

**Issue by Markell** [petereon/beaupy#101]
Hi 👋
I don't understand how to implement `select_multiple` if the `esc` key is pressed, because for my program an empty list means deleting all data. I tried to work with `raise_on_escape` exception but no concise solution came out.
I am new to python and may not see an obvious solution, but please help me out 🙏

**Comment by petereon** [comment]
Hi, apologies for a late response.

For handling `ESC` and `CTRL+C` keys in `beaupy` you need to set the appropriate `Config` options and then handle arising exceptions in Python's [`try-except`](https://docs.python.org/3/tutorial/errors.html#handling-exceptions) construct. 

Consider the following example:
```python
from beaupy import Config, Abort, select_multiple

Config.raise_on_escape = True
Config.raise_on_interrupt = True

try:
    items = select_multiple(["One", "Two", "Three"], maximal_count=2)
    print("Selected items:", items)
except Abort:
    print("Pressed ESC")
except KeyboardInterrupt:
    print("Pressed Ctrl+C")
```

⚠️  Note if you allocate items prior to entering the `try-except` block (illustrated below) it will still end up being an empty list. `beaupy` upholds its types so the `select_multiple` will always return a `List`.

```python
# truncated for brevity

items = []

try:
    items = select_multiple(["One", "Two", "Three"], maximal_count=2)
    print("Selected items:", items)
except Abort:
    print("Pressed ESC")
except KeyboardInterrupt:
    print("Pressed Ctrl+C")
    
print(items) # <- `items` will be empty if ESC or Ctrl+C was pressed
```

Let me know if this fulfills your requirements.
