### ISSUE TITLE
Behaviour difference between 3.8.3 and 3.9.# Lack of screen wipe following user selection.

### ISSUE THREAD

**Issue by A-nglea** [petereon/beaupy#108]
![Select no longer wipes after selection](https://github.com/user-attachments/assets/7e700a94-9c8d-488a-a8e9-881d03715398)

The behaviour above is the result of 3 select statements and two choices. It is the result produced by beaupy 3.9.1 whereas 3.8.3 wiped itself away after each selection was made. 

Not a big deal as I can add code to correct, but better if updates don't upset what has gone before. Was it intentional or just an artefact arising from the change?

I love this module to  bits and am grateful for its upkeep!

**Comment by petereon** [comment]
Thanks for reporting. This is a new feature from `3.9.0` but the intention was to leave the wiping as default, which I have apparently failed to do. 

Sorry for breakage. I'll look into it soon.

**Comment by petereon** [comment]
Fix is available in [3.9.2](https://pypi.org/project/beaupy/3.9.2/)

**Comment by A-nglea** [comment]
Thanks very much, Peter,  for a speedy response!
