### ISSUE TITLE
Vim bindings

### ISSUE THREAD

**Issue by atkinsg** [petereon/beaupy#110]
Is it possible to allow Vim key bindings, j: down and k: up, for the select and select_multiple functions?

**Comment by petereon** [comment]
This is supported - see [`DefaultKeys` class](https://github.com/petereon/beaupy/blob/95d8b9298728d437a19f8bacf28ec24ff2a51368/beaupy/_beaupy.py#L39) that acts as a global config. You can set up something like:

```py
from beaupy import DefaultKeys

DefaultKeys.down.append('j')
DefaultKeys.up.append('k')
```

Note: haven't tested the code, but should capture the general gist.

**Comment by atkinsg** [comment]
That's beautiful. It works just as I had hoped. Thank you very much.

Here is my sample.

```
from pathlib import Path

from beaupy import select
from beaupy import DefaultKeys
import click

DOWNLOADS = '/Users/xxxxxx/downloads'

DefaultKeys.down.append('j')
DefaultKeys.up.append('k')

@click.command()
def cli():
    files = [path for path in Path(DOWNLOADS).glob('I_Can*')]
    index = select(files, return_index=True)
    if index:
        click.echo(files[index])

if __name__ == '__main__':
    cli()
```

**Comment by petereon** [comment]
Glad it works for you! I'll be closing the issue. Feel free to open another in case there are more questions or some bug.
