### ISSUE TITLE
Link update for passgen. [Non Issue - Documentation]

### ISSUE THREAD

**Issue by therealOri** [petereon/beaupy#39]
Just wanted to drop by and say that the url https://github.com/therealOri/PassGen is no longer the correct name for the project. I have updated its name and is now a bit more official.

https://github.com/therealOri/Genter is the new url/name for the project.

~~I have also updated another one of my projects to use beaupy if you are interested in showcasing it as well~~

**Comment by petereon** [comment]
Hey Ori. Updated already! Please feel free to drop a link to a new project using beaupy. I'd love to take a look.

**Comment by therealOri** [comment]
> Hey Ori. Updated already! Please feel free to drop a link to a new project using beaupy. I'd love to take a look.

Here's my other project that I have brought beaupy to,: https://github.com/therealOri/byte

**Comment by petereon** [comment]
Hey @therealOri, sorry, I've been super busy and kinda forgot. Very cool project, added it now!
