### ISSUE TITLE
amazingly works on Windows

### ISSUE THREAD

**Issue by epogrebnyak** [petereon/beaupy#52]
I'm making some code for a class in university and trying several packages to do select the options as students usually like some interactivity. Most packages fail or unstable on Windows while beaupy works like a charm! 

Thanks for the package!

**Comment by petereon** [comment]
Glad it works for you! If you have some ideas and suggestions from working with package I'd love to hear them.

**Comment by petereon** [comment]
Closing! Feel free to open a new issue if you encounter bugs or would like to request features.
