### ISSUE TITLE
documentation idea (no main())

### ISSUE THREAD

**Issue by epogrebnyak** [petereon/beaupy#53]
Have you though of gettign rid of main in a starter example? Iwthout main people can easily use code right away.
 
```
def main():
    """Main."""
    # Confirm a dialog
```

**Comment by epogrebnyak** [comment]
Here is asimplfied example I used to start with beaupy

```
from beaupy import confirm, console, select

names = [
        "Frodo Baggins",
        "Samwise Gamgee",
        "Legolas",
        "Aragorn",
        "[red]Sauron[/red]",
    ]

if confirm("Will you take the ring to Mordor?"):
    console.print("Who are you?")
    name = select(names, cursor="🢧", cursor_style="cyan")
    console.print("Alámenë", name)
```

**Comment by petereon** [comment]
This is a good point, `if __name__=='__main__'` block might be a bit confusing for people who are new to Python, despite being a best practice. I am going to adjust that and remove `main` in the next release.

**Comment by petereon** [comment]
Done! Thanks for a suggestion!
