### ISSUE TITLE
select_multiple scrolling feature if number of options exceed console size

### ISSUE THREAD

**Issue by SamLo322** [petereon/beaupy#55]
I made a list with over 40 options available for use to select on, but the console size isn't enough to show all of the item_options. Is there any way to scroll the options ? (Or some features like chosen option stay on the middle while the whole list shift up every time I hit the down arrow until it reaches the last option)

**Comment by petereon** [comment]
Hi @SamLo322, thank you for the issue. 

This is currently a limitation, there is not way to have scrolling or pagination for the options. 

I am accepting pull requests, so if you'd like to have a go at this yourself, feel free. Otherwise, I am going to have a look at this over the weekend.

**Comment by petereon** [comment]
Released in [v3.5.0](https://github.com/petereon/beaupy/releases/tag/v3.5.0)

**Comment by SamLo322** [comment]
Thank you soooo much. Really helps a lot~ :D

**Comment by petereon** [comment]
Glad to have helped, I should mention that `3.5.0` and `3.5.1` are buggy.
