### ISSUE TITLE
Possibility to underline current option in select_multiple

### ISSUE THREAD

**Issue by juxeii** [petereon/beaupy#67]
Hi,

would it be much work to underline the current option in `select_multiple` which is chosen with the up/down keys?
I have pre-colored some options red and some blue. 
And the third color green is for the current selected option.
But this hides the pre-color. So, instead of specifying a selection-color, it may make sense to underline the current option.
This way, the user would always see the pre-colors(which my represent different semantics).

**Comment by petereon** [comment]
Hi @juxeii 

If I understand your requirement correctly, setting `cursor_style='underline'` should cover your use-case?

**Comment by juxeii** [comment]
That is exactly what I need, thx!
Is there a comprehensive list of all the options available? I thought that only colors would be allowed.

**Comment by petereon** [comment]
Glad it worked!

> Is there a comprehensive list of all the options available?

Yes, you can refer to [**Styles** section of `rich` documentation](https://rich.readthedocs.io/en/stable/style.html). Note that currently only "string represented styles" are supported. I plan to support `Style` objects in the future.

**Comment by juxeii** [comment]
Thank you!
