### ISSUE TITLE
Pagination: cannot get it to work

### ISSUE THREAD

**Issue by A-nglea** [petereon/beaupy#73]
videos = select_multiple(beaupylist, ticked_indices=index, minimal_count=1, page_size=20, pagination=True)

Seems to have no effect with beaupylist containing 110 items. The cursor appears to scroll over them but disappears off the page. I can even select from off the page but am unable to see it. There are ellipses ... at the page bottom but I cannot get the page to scroll.
I'm sure its 'operator error' what am I missing?

**Comment by petereon** [comment]
I'll try to reproduce

**Comment by petereon** [comment]
Can't reproduce with `beaupy==3.5.4`, what version of `beaupy` are you using (`pip show beaupy`)?

Bugs like this were present `beaupy<3.5.4,>=3.5.0`.

**Comment by A-nglea** [comment]
Working now. Operator error!

**Comment by petereon** [comment]
@A-nglea, thanks for closing. If this is a library-specific limitation please do share more details, as I am unaware.
