### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by amiguet** [petereon/beaupy#78]
Hello,

Just discovering beaupy, nice useful project!

However, even a simplistic code like

```python
from beaupy import select

item_options = [
    "o1",
    "o2",
    "o3",
]
items = select(item_options)
```

uses 100% of my cpu.

Python 3.11.5 on Linux, beaupy 3.6.0 installed in a venv via pip.

Any idea what is happening?

**Comment by petereon** [comment]
Never had this happen. I will try to reproduce this today.

**Comment by amiguet** [comment]
Yeah, I just noticed this comes from yakh. Closing here, opening there!
