### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by petereon** [petereon/beaupy#86]
Ward is causing issues with Python 3.12: https://github.com/darrenburns/ward/issues/374

There is a pull request that deals with this: https://github.com/darrenburns/ward/pull/373

As soon as this gets merged `ward` should be updated and Python version constraint relaxed.

**Comment by ashb** [comment]
Loving this module -- any chance of a pypi release please?

**Comment by petereon** [comment]
On it!

**Comment by petereon** [comment]
Sorry, it was a bit more work than I hoped for, but there is now `beaupy==3.7.3` available on [PyPI](https://pypi.org/project/beaupy/3.7.3/)
