### ISSUE TITLE
KeyboardInterrupt exception in select_multiple

### ISSUE THREAD

**Issue by Schwitzd** [petereon/beaupy#94]
I have this code snipped: 
```python
try:
    selected_apps = select_multiple(bloatware_detected, pagination=True, page_size=20)
except KeyboardInterrupt as ki:
    raise SystemExit() from ki
```

When I press CTRL+C during the selection the KeyboardInterrupt exception is bypassed.

I'm using the latest release of beaupy.

Cheers

**Comment by petereon** [comment]
Default behavior among all the CLI elements of `beaupy` is not to raise on keyboard interrupt. If you'd prefer it to raise, you can set this behavior as follows:
```py
from beaupy import select_multiple, Config

Config.raise_on_interrupt = True

try:
    selected_apps = select_multiple(bloatware_detected, pagination=True, page_size=20)
except KeyboardInterrupt as ki:
    raise SystemExit() from ki
```

Please let me know if this fits your use case.

**Comment by Schwitzd** [comment]
wooow so fast, exactly what I was looking for <3
